# =============================================================================
# scripts/vivado/synth_driver.cmake — Vivado synthesis + implementation driver
#
# Invoked by CTest via:
#   cmake -D<vars> -P scripts/vivado/synth_driver.cmake
#
# Required -D variables (all set by targets.cmake):
#   VIVADO_EXE      absolute path to vivado binary
#   TOP_MODULE      top-level SystemVerilog module name
#   PART            Xilinx device part string  (e.g. xc7a35tcpg236-1)
#   RTL_FILES       pipe-separated RTL .sv paths
#   XDC_FILE        absolute path to XDC constraints file (may be empty)
#   WORK_DIR        per-run output directory
#
# Outputs written to WORK_DIR:
#   <top>.bit               — bitstream
#   <top>_post_route.dcp    — routed design checkpoint
#   timing.rpt              — timing summary report
#   util.rpt                — utilisation report
#   run_synth.tcl           — generated TCL (kept for debug)
#   vivado.log              — Vivado session log
#   vivado.jou              — Vivado journal
# =============================================================================

cmake_minimum_required(VERSION 3.20)

# =============================================================================
# Validate
# =============================================================================
foreach(_var VIVADO_EXE TOP_MODULE PART RTL_FILES WORK_DIR)
    if(NOT DEFINED ${_var} OR "${${_var}}" STREQUAL "")
        message(FATAL_ERROR "[synth_driver] Missing required variable: ${_var}")
    endif()
endforeach()

string(REPLACE "|" ";" _rtl_list "${RTL_FILES}")

# =============================================================================
# Generate the Vivado TCL script
# =============================================================================
# Using non-project (Tcl) mode — no .xpr file, fully reproducible, CI-friendly.
set(_tcl_path "${WORK_DIR}/run_synth.tcl")

# Build the file list as a Tcl list literal
set(_tcl_files "")
foreach(_f ${_rtl_list})
    string(APPEND _tcl_files "    {${_f}}\n")
endforeach()

set(_xdc_block "")
if(XDC_FILE AND EXISTS "${XDC_FILE}")
    set(_xdc_block "read_xdc {${XDC_FILE}}\n")
endif()

file(WRITE "${_tcl_path}"
"# Auto-generated by synth_driver.cmake — do not edit manually.
# Re-run cmake to regenerate.

# ── Source files ─────────────────────────────────────────────────────────────
read_verilog -sv [list
${_tcl_files}]

# ── Constraints ───────────────────────────────────────────────────────────────
${_xdc_block}
# ── Synthesis ─────────────────────────────────────────────────────────────────
synth_design -top ${TOP_MODULE} -part ${PART} -flatten_hierarchy rebuilt

# ── Implementation ────────────────────────────────────────────────────────────
opt_design
place_design
phys_opt_design
route_design

# ── Outputs ───────────────────────────────────────────────────────────────────
write_bitstream  -force {${WORK_DIR}/${TOP_MODULE}.bit}
write_checkpoint -force {${WORK_DIR}/${TOP_MODULE}_post_route.dcp}
report_timing_summary -file {${WORK_DIR}/timing.rpt}
report_utilization    -file {${WORK_DIR}/util.rpt}
report_power          -file {${WORK_DIR}/power.rpt}

puts {[SYNTH] PASSED — ${TOP_MODULE}}
"
)

# =============================================================================
# Run Vivado in batch mode
# =============================================================================
message("[SYNTH] Starting synthesis: ${TOP_MODULE}  part=${PART}")
message("[SYNTH] TCL: ${_tcl_path}")
message("[SYNTH] Output dir: ${WORK_DIR}")

execute_process(
    COMMAND "${VIVADO_EXE}"
        -mode batch
        -source "${_tcl_path}"
        -log    "${WORK_DIR}/vivado.log"
        -journal "${WORK_DIR}/vivado.jou"
        -nojournal
    WORKING_DIRECTORY "${WORK_DIR}"
    RESULT_VARIABLE _rc
    OUTPUT_VARIABLE _out
    ERROR_VARIABLE  _err
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_STRIP_TRAILING_WHITESPACE
)

if(_out)
    message("${_out}")
endif()
if(_err)
    message("${_err}")
endif()

if(NOT _rc EQUAL 0)
    message("[SYNTH] FAILED — Vivado exited with code ${_rc}")
    message("  Log: ${WORK_DIR}/vivado.log")
    cmake_language(EXIT 1)
endif()

# Verify bitstream was actually produced
if(NOT EXISTS "${WORK_DIR}/${TOP_MODULE}.bit")
    message("[SYNTH] FAILED — bitstream not found: ${WORK_DIR}/${TOP_MODULE}.bit")
    message("  Check ${WORK_DIR}/vivado.log for timing/DRC failures.")
    cmake_language(EXIT 1)
endif()

message("[SYNTH] PASSED — ${TOP_MODULE}")
message("  Bitstream : ${WORK_DIR}/${TOP_MODULE}.bit")
message("  Timing    : ${WORK_DIR}/timing.rpt")
message("  Util      : ${WORK_DIR}/util.rpt")
